version: "3.8"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SicnoLab2025
      MYSQL_DATABASE: dbmastertest
    ports:
      - "3306:3306"
  
  python-app:
    build: .
    depends_on:
      - mysql
